[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "noradefitero", email = "nora@defitero.com" }]
requires-python = ">=3.10"
dependencies = ["pydantic>=2.13.5", "typer>=0.27.2"]

[project.scripts]
call-me-maybe = "call_me_maybe:app"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[dependency-groups]
dev = ["flake8>=7.3.0", "mypy>=2.3.1", "pre-commit>=4.6.2", "ruff>=0.16.8"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
